# This file is part of Astarte.
#
# Copyright 2022 SECO Mind Srl
#
# SPDX-License-Identifier: CC0-1.0


[package]
name = "astarte-message-hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.2"
prost = "0.11.0"
pbjson-types = "0.5"
chrono = "0.4.22"
thiserror = "1.0"
astarte_sdk = {git ="https://github.com/astarte-platform/astarte-device-sdk-rust.git" }
serde = "1.0.147"

[build-dependencies]
tonic-build = "0.8.2"
